Stop-Process -ProcessName CarXmlConvertor.exe -ErrorAction SilentlyContinue
Stop-Process -ProcessName CarXmlConvertor.exe.config -ErrorAction SilentlyContinue
Stop-Process -ProcessName ObjectBender.exe -ErrorAction SilentlyContinue
Stop-Process -ProcessName ObjectBender.exe.config -ErrorAction SilentlyContinue
Stop-Process -ProcessName ObjectViewer.exe -ErrorAction SilentlyContinue
Stop-Process -ProcessName ObjectViewer.exe.config -ErrorAction SilentlyContinue
Stop-Process -ProcessName OpenBve-32.exe -ErrorAction SilentlyContinue
Stop-Process -ProcessName OpenBve.exe -ErrorAction SilentlyContinue
Stop-Process -ProcessName RouteViewer-32.exe -ErrorAction SilentlyContinue
Stop-Process -ProcessName RouteViewer-32.exe.config -ErrorAction SilentlyContinue
Stop-Process -ProcessName RouteViewer.exe -ErrorAction SilentlyContinue
Stop-Process -ProcessName RouteViewer.exe.config -ErrorAction SilentlyContinue
Stop-Process -ProcessName TrainEditor.exe -ErrorAction SilentlyContinue
Stop-Process -ProcessName TrainEditor.exe.config -ErrorAction SilentlyContinue
Stop-Process -ProcessName TrainEditor2.exe -ErrorAction SilentlyContinue
Stop-Process -ProcessName TrainEditor2.exe.config -ErrorAction SilentlyContinue
Stop-Process -ProcessName Uninstal.exe -ErrorAction SilentlyContinue
Stop-Process -ProcessName Win32PluginProxy.exe -ErrorAction SilentlyContinue
Stop-Process -ProcessName Win32PluginProxy.exe.config -ErrorAction SilentlyContinue
Stop-Process -ProcessName unins000.exe -ErrorAction SilentlyContinue
